server:
  port: 9595
  max-http-header-size: 8096
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost/clock_mall?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
      view:
        suffix: .html
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-wait: 30000ms     #连接池最大阻塞等待时间(负值表示没有限制)
        max-active: 100       #连接池最大连接数(负值表示没有限制)
        max-idle: 20          #连接池中最大空闲连接
        min-idle: 0           #连接池中最小空闲连接
    timeout: 3000ms
mybatis-plus:
  type-aliases-package: com.example.clockmallservice.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.example.clockmallservice.mapper: debug
